name: hey_milo
description: "Record Memories, Connect with Caregivers & Manage Medication"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #Utilities
  get_it: ^7.6.4
  permission_handler: ^12.0.0+1
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.5.0
  
  # Only include if you need notifications right away
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

  #Audio - the most critical part for your app's functionality
  record: ^6.0.0
  just_audio: ^0.9.35
  audio_session: ^0.1.16
  share_plus: ^11.0.0

  #local storage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  
  # Move this to dev_dependencies since it's only used during development

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

# This should be outside the flutter section
flutter_native_splash:
  android: true
  ios: true
  color: "#121212"  # Background color of the splash screen
  
  
  # Fullscreen splash
  fullscreen: true
  
  # Android 12 configuration
  android_12:
    
    icon_background_color: "#121212"
  
  # Positioning
  android_gravity: center
  ios_content_mode: center

